name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add environment variables
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          NOMIC_API_KEY: ${{ secrets.NOMIC_API_KEY }}
        run: |
          echo "GROQ_API_KEY=${GROQ_API_KEY}" >> $GITHUB_ENV
          echo "NOMIC_API_KEY=${NOMIC_API_KEY}" >> $GITHUB_ENV

      - name: Run Streamlit
        run: |
          streamlit run main.py
